#----------------------------------------------------------------
# Generated CMake target import file for configuration "Release".
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Import target "TKernel" for configuration "Release"
set_property(TARGET TKernel APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKernel PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win32/lib/TKernel.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "ws2_32;advapi32;gdi32;user32;kernel32;psapi"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win32/bin/TKernel.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKernel )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKernel "${_IMPORT_PREFIX}/Win32/lib/TKernel.lib" "${_IMPORT_PREFIX}/Win32/bin/TKernel.dll" )

# Import target "TKMath" for configuration "Release"
set_property(TARGET TKMath APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKMath PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win32/lib/TKMath.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKernel"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win32/bin/TKMath.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKMath )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKMath "${_IMPORT_PREFIX}/Win32/lib/TKMath.lib" "${_IMPORT_PREFIX}/Win32/bin/TKMath.dll" )

# Import target "TKG2d" for configuration "Release"
set_property(TARGET TKG2d APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKG2d PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win32/lib/TKG2d.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKernel;TKMath"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win32/bin/TKG2d.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKG2d )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKG2d "${_IMPORT_PREFIX}/Win32/lib/TKG2d.lib" "${_IMPORT_PREFIX}/Win32/bin/TKG2d.dll" )

# Import target "TKG3d" for configuration "Release"
set_property(TARGET TKG3d APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKG3d PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win32/lib/TKG3d.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKMath;TKernel;TKG2d"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win32/bin/TKG3d.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKG3d )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKG3d "${_IMPORT_PREFIX}/Win32/lib/TKG3d.lib" "${_IMPORT_PREFIX}/Win32/bin/TKG3d.dll" )

# Import target "TKGeomBase" for configuration "Release"
set_property(TARGET TKGeomBase APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKGeomBase PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win32/lib/TKGeomBase.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKernel;TKMath;TKG2d;TKG3d"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win32/bin/TKGeomBase.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKGeomBase )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKGeomBase "${_IMPORT_PREFIX}/Win32/lib/TKGeomBase.lib" "${_IMPORT_PREFIX}/Win32/bin/TKGeomBase.dll" )

# Import target "TKBRep" for configuration "Release"
set_property(TARGET TKBRep APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKBRep PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win32/lib/TKBRep.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKMath;TKernel;TKG2d;TKG3d;TKGeomBase"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win32/bin/TKBRep.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKBRep )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKBRep "${_IMPORT_PREFIX}/Win32/lib/TKBRep.lib" "${_IMPORT_PREFIX}/Win32/bin/TKBRep.dll" )

# Import target "TKGeomAlgo" for configuration "Release"
set_property(TARGET TKGeomAlgo APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKGeomAlgo PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win32/lib/TKGeomAlgo.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKernel;TKMath;TKG3d;TKG2d;TKGeomBase;TKBRep"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win32/bin/TKGeomAlgo.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKGeomAlgo )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKGeomAlgo "${_IMPORT_PREFIX}/Win32/lib/TKGeomAlgo.lib" "${_IMPORT_PREFIX}/Win32/bin/TKGeomAlgo.dll" )

# Import target "TKTopAlgo" for configuration "Release"
set_property(TARGET TKTopAlgo APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKTopAlgo PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win32/lib/TKTopAlgo.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKMath;TKernel;TKG2d;TKG3d;TKGeomBase;TKBRep;TKGeomAlgo"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win32/bin/TKTopAlgo.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKTopAlgo )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKTopAlgo "${_IMPORT_PREFIX}/Win32/lib/TKTopAlgo.lib" "${_IMPORT_PREFIX}/Win32/bin/TKTopAlgo.dll" )

# Import target "TKPrim" for configuration "Release"
set_property(TARGET TKPrim APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKPrim PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win32/lib/TKPrim.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKBRep;TKernel;TKMath;TKG2d;TKGeomBase;TKG3d;TKTopAlgo"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win32/bin/TKPrim.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKPrim )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKPrim "${_IMPORT_PREFIX}/Win32/lib/TKPrim.lib" "${_IMPORT_PREFIX}/Win32/bin/TKPrim.dll" )

# Import target "TKBO" for configuration "Release"
set_property(TARGET TKBO APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKBO PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win32/lib/TKBO.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKBRep;TKTopAlgo;TKMath;TKernel;TKG2d;TKG3d;TKGeomAlgo;TKGeomBase;TKPrim"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win32/bin/TKBO.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKBO )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKBO "${_IMPORT_PREFIX}/Win32/lib/TKBO.lib" "${_IMPORT_PREFIX}/Win32/bin/TKBO.dll" )

# Import target "TKHLR" for configuration "Release"
set_property(TARGET TKHLR APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKHLR PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win32/lib/TKHLR.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKBRep;TKernel;TKMath;TKGeomBase;TKG2d;TKG3d;TKGeomAlgo;TKTopAlgo"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win32/bin/TKHLR.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKHLR )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKHLR "${_IMPORT_PREFIX}/Win32/lib/TKHLR.lib" "${_IMPORT_PREFIX}/Win32/bin/TKHLR.dll" )

# Import target "TKMesh" for configuration "Release"
set_property(TARGET TKMesh APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKMesh PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win32/lib/TKMesh.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKBRep;TKMath;TKernel;TKG2d;TKG3d;TKGeomBase;TKTopAlgo;TKGeomAlgo"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win32/bin/TKMesh.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKMesh )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKMesh "${_IMPORT_PREFIX}/Win32/lib/TKMesh.lib" "${_IMPORT_PREFIX}/Win32/bin/TKMesh.dll" )

# Import target "TKShHealing" for configuration "Release"
set_property(TARGET TKShHealing APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKShHealing PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win32/lib/TKShHealing.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKBRep;TKernel;TKMath;TKG2d;TKTopAlgo;TKG3d;TKGeomBase;TKGeomAlgo;ws2_32"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win32/bin/TKShHealing.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKShHealing )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKShHealing "${_IMPORT_PREFIX}/Win32/lib/TKShHealing.lib" "${_IMPORT_PREFIX}/Win32/bin/TKShHealing.dll" )

# Import target "TKXMesh" for configuration "Release"
set_property(TARGET TKXMesh APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKXMesh PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win32/lib/TKXMesh.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKBRep;TKMath;TKernel;TKG2d;TKMesh"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win32/bin/TKXMesh.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKXMesh )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKXMesh "${_IMPORT_PREFIX}/Win32/lib/TKXMesh.lib" "${_IMPORT_PREFIX}/Win32/bin/TKXMesh.dll" )

# Import target "TKBool" for configuration "Release"
set_property(TARGET TKBool APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKBool PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win32/lib/TKBool.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKBRep;TKTopAlgo;TKMath;TKernel;TKPrim;TKG2d;TKG3d;TKShHealing;TKGeomBase;TKGeomAlgo;TKBO"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win32/bin/TKBool.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKBool )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKBool "${_IMPORT_PREFIX}/Win32/lib/TKBool.lib" "${_IMPORT_PREFIX}/Win32/bin/TKBool.dll" )

# Import target "TKFillet" for configuration "Release"
set_property(TARGET TKFillet APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKFillet PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win32/lib/TKFillet.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKBRep;TKernel;TKMath;TKGeomBase;TKGeomAlgo;TKG2d;TKTopAlgo;TKG3d;TKBool;TKShHealing"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win32/bin/TKFillet.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKFillet )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKFillet "${_IMPORT_PREFIX}/Win32/lib/TKFillet.lib" "${_IMPORT_PREFIX}/Win32/bin/TKFillet.dll" )

# Import target "TKFeat" for configuration "Release"
set_property(TARGET TKFeat APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKFeat PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win32/lib/TKFeat.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKBRep;TKTopAlgo;TKGeomAlgo;TKMath;TKernel;TKGeomBase;TKPrim;TKG2d;TKBO;TKG3d;TKBool"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win32/bin/TKFeat.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKFeat )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKFeat "${_IMPORT_PREFIX}/Win32/lib/TKFeat.lib" "${_IMPORT_PREFIX}/Win32/bin/TKFeat.dll" )

# Import target "TKOffset" for configuration "Release"
set_property(TARGET TKOffset APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKOffset PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win32/lib/TKOffset.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKFillet;TKBRep;TKTopAlgo;TKMath;TKernel;TKGeomBase;TKG2d;TKG3d;TKGeomAlgo;TKShHealing;TKBO;TKPrim;TKBool"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win32/bin/TKOffset.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKOffset )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKOffset "${_IMPORT_PREFIX}/Win32/lib/TKOffset.lib" "${_IMPORT_PREFIX}/Win32/bin/TKOffset.dll" )

# Import target "TKCDF" for configuration "Release"
set_property(TARGET TKCDF APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKCDF PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win32/lib/TKCDF.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKernel"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win32/bin/TKCDF.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKCDF )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKCDF "${_IMPORT_PREFIX}/Win32/lib/TKCDF.lib" "${_IMPORT_PREFIX}/Win32/bin/TKCDF.dll" )

# Import target "PTKernel" for configuration "Release"
set_property(TARGET PTKernel APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(PTKernel PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win32/lib/PTKernel.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKernel"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win32/bin/PTKernel.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS PTKernel )
list(APPEND _IMPORT_CHECK_FILES_FOR_PTKernel "${_IMPORT_PREFIX}/Win32/lib/PTKernel.lib" "${_IMPORT_PREFIX}/Win32/bin/PTKernel.dll" )

# Import target "TKLCAF" for configuration "Release"
set_property(TARGET TKLCAF APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKLCAF PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win32/lib/TKLCAF.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKCDF;TKernel"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win32/bin/TKLCAF.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKLCAF )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKLCAF "${_IMPORT_PREFIX}/Win32/lib/TKLCAF.lib" "${_IMPORT_PREFIX}/Win32/bin/TKLCAF.dll" )

# Import target "FWOSPlugin" for configuration "Release"
set_property(TARGET FWOSPlugin APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(FWOSPlugin PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win32/lib/FWOSPlugin.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKernel;TKCDF"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win32/bin/FWOSPlugin.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS FWOSPlugin )
list(APPEND _IMPORT_CHECK_FILES_FOR_FWOSPlugin "${_IMPORT_PREFIX}/Win32/lib/FWOSPlugin.lib" "${_IMPORT_PREFIX}/Win32/bin/FWOSPlugin.dll" )

# Import target "TKPShape" for configuration "Release"
set_property(TARGET TKPShape APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKPShape PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win32/lib/TKPShape.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKMath;TKernel;TKG2d;TKG3d;PTKernel;TKBRep"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win32/bin/TKPShape.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKPShape )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKPShape "${_IMPORT_PREFIX}/Win32/lib/TKPShape.lib" "${_IMPORT_PREFIX}/Win32/bin/TKPShape.dll" )

# Import target "TKBinL" for configuration "Release"
set_property(TARGET TKBinL APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKBinL PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win32/lib/TKBinL.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKCDF;TKernel;TKLCAF"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win32/bin/TKBinL.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKBinL )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKBinL "${_IMPORT_PREFIX}/Win32/lib/TKBinL.lib" "${_IMPORT_PREFIX}/Win32/bin/TKBinL.dll" )

# Import target "TKXmlL" for configuration "Release"
set_property(TARGET TKXmlL APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKXmlL PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win32/lib/TKXmlL.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKCDF;TKernel;TKMath;TKLCAF"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win32/bin/TKXmlL.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKXmlL )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKXmlL "${_IMPORT_PREFIX}/Win32/lib/TKXmlL.lib" "${_IMPORT_PREFIX}/Win32/bin/TKXmlL.dll" )

# Import target "TKPLCAF" for configuration "Release"
set_property(TARGET TKPLCAF APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKPLCAF PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win32/lib/TKPLCAF.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKCDF;PTKernel;TKernel;TKLCAF"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win32/bin/TKPLCAF.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKPLCAF )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKPLCAF "${_IMPORT_PREFIX}/Win32/lib/TKPLCAF.lib" "${_IMPORT_PREFIX}/Win32/bin/TKPLCAF.dll" )

# Import target "TKTObj" for configuration "Release"
set_property(TARGET TKTObj APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKTObj PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win32/lib/TKTObj.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKCDF;TKernel;TKMath;TKLCAF"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win32/bin/TKTObj.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKTObj )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKTObj "${_IMPORT_PREFIX}/Win32/lib/TKTObj.lib" "${_IMPORT_PREFIX}/Win32/bin/TKTObj.dll" )

# Import target "TKShapeSchema" for configuration "Release"
set_property(TARGET TKShapeSchema APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKShapeSchema PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win32/lib/TKShapeSchema.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKernel;TKG2d;PTKernel;TKMath;TKCDF;TKPShape"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win32/bin/TKShapeSchema.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKShapeSchema )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKShapeSchema "${_IMPORT_PREFIX}/Win32/lib/TKShapeSchema.lib" "${_IMPORT_PREFIX}/Win32/bin/TKShapeSchema.dll" )

# Import target "TKStdLSchema" for configuration "Release"
set_property(TARGET TKStdLSchema APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKStdLSchema PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win32/lib/TKStdLSchema.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKCDF;PTKernel;TKernel;TKShapeSchema;TKLCAF;TKPLCAF"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win32/bin/TKStdLSchema.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKStdLSchema )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKStdLSchema "${_IMPORT_PREFIX}/Win32/lib/TKStdLSchema.lib" "${_IMPORT_PREFIX}/Win32/bin/TKStdLSchema.dll" )

# Import target "TKSTL" for configuration "Release"
set_property(TARGET TKSTL APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKSTL PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win32/lib/TKSTL.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKernel;TKMath;TKBRep;TKG2d;TKG3d;TKMesh;TKTopAlgo"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win32/bin/TKSTL.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKSTL )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKSTL "${_IMPORT_PREFIX}/Win32/lib/TKSTL.lib" "${_IMPORT_PREFIX}/Win32/bin/TKSTL.dll" )

# Import target "TKXSBase" for configuration "Release"
set_property(TARGET TKXSBase APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKXSBase PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win32/lib/TKXSBase.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKBRep;TKernel;TKMath;TKG2d;TKG3d;TKTopAlgo;TKGeomBase;TKShHealing"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win32/bin/TKXSBase.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKXSBase )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKXSBase "${_IMPORT_PREFIX}/Win32/lib/TKXSBase.lib" "${_IMPORT_PREFIX}/Win32/bin/TKXSBase.dll" )

# Import target "TKSTEPBase" for configuration "Release"
set_property(TARGET TKSTEPBase APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKSTEPBase PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win32/lib/TKSTEPBase.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKernel;TKXSBase;TKMath"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win32/bin/TKSTEPBase.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKSTEPBase )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKSTEPBase "${_IMPORT_PREFIX}/Win32/lib/TKSTEPBase.lib" "${_IMPORT_PREFIX}/Win32/bin/TKSTEPBase.dll" )

# Import target "TKIGES" for configuration "Release"
set_property(TARGET TKIGES APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKIGES PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win32/lib/TKIGES.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKBRep;TKernel;TKMath;TKTopAlgo;TKShHealing;TKG2d;TKG3d;TKGeomBase;TKGeomAlgo;TKPrim;TKBool;TKOffset;TKXSBase"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win32/bin/TKIGES.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKIGES )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKIGES "${_IMPORT_PREFIX}/Win32/lib/TKIGES.lib" "${_IMPORT_PREFIX}/Win32/bin/TKIGES.dll" )

# Import target "TKSTEPAttr" for configuration "Release"
set_property(TARGET TKSTEPAttr APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKSTEPAttr PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win32/lib/TKSTEPAttr.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKernel;TKXSBase;TKSTEPBase"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win32/bin/TKSTEPAttr.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKSTEPAttr )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKSTEPAttr "${_IMPORT_PREFIX}/Win32/lib/TKSTEPAttr.lib" "${_IMPORT_PREFIX}/Win32/bin/TKSTEPAttr.dll" )

# Import target "TKSTEP209" for configuration "Release"
set_property(TARGET TKSTEP209 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKSTEP209 PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win32/lib/TKSTEP209.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKernel;TKXSBase;TKSTEPBase"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win32/bin/TKSTEP209.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKSTEP209 )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKSTEP209 "${_IMPORT_PREFIX}/Win32/lib/TKSTEP209.lib" "${_IMPORT_PREFIX}/Win32/bin/TKSTEP209.dll" )

# Import target "TKSTEP" for configuration "Release"
set_property(TARGET TKSTEP APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKSTEP PROPERTIES
  IMPORTED_IMPLIB_RELEASE "${_IMPORT_PREFIX}/Win32/lib/TKSTEP.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "TKernel;TKSTEPAttr;TKSTEP209;TKSTEPBase;TKBRep;TKMath;TKG2d;TKShHealing;TKTopAlgo;TKG3d;TKGeomBase;TKGeomAlgo;TKXSBase;ws2_32"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/Win32/bin/TKSTEP.dll"
  )

list(APPEND _IMPORT_CHECK_TARGETS TKSTEP )
list(APPEND _IMPORT_CHECK_FILES_FOR_TKSTEP "${_IMPORT_PREFIX}/Win32/lib/TKSTEP.lib" "${_IMPORT_PREFIX}/Win32/bin/TKSTEP.dll" )

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
