# Generated by CMake 3.4.0

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget TKernel TKMath TKG2d TKG3d TKGeomBase TKBRep TKGeomAlgo TKTopAlgo TKPrim TKBO TKHLR TKMesh TKShHealing TKXMesh TKBool TKFillet TKFeat TKOffset TKCDF PTKernel TKLCAF FWOSPlugin TKPShape TKBinL TKXmlL TKPLCAF TKTObj TKShapeSchema TKStdLSchema TKSTL TKXSBase TKSTEPBase TKIGES TKSTEPAttr TKSTEP209 TKSTEP)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)

# Create imported target TKernel
add_library(TKernel SHARED IMPORTED)

# Create imported target TKMath
add_library(TKMath SHARED IMPORTED)

# Create imported target TKG2d
add_library(TKG2d SHARED IMPORTED)

# Create imported target TKG3d
add_library(TKG3d SHARED IMPORTED)

# Create imported target TKGeomBase
add_library(TKGeomBase SHARED IMPORTED)

# Create imported target TKBRep
add_library(TKBRep SHARED IMPORTED)

# Create imported target TKGeomAlgo
add_library(TKGeomAlgo SHARED IMPORTED)

# Create imported target TKTopAlgo
add_library(TKTopAlgo SHARED IMPORTED)

# Create imported target TKPrim
add_library(TKPrim SHARED IMPORTED)

# Create imported target TKBO
add_library(TKBO SHARED IMPORTED)

# Create imported target TKHLR
add_library(TKHLR SHARED IMPORTED)

# Create imported target TKMesh
add_library(TKMesh SHARED IMPORTED)

# Create imported target TKShHealing
add_library(TKShHealing SHARED IMPORTED)

# Create imported target TKXMesh
add_library(TKXMesh SHARED IMPORTED)

# Create imported target TKBool
add_library(TKBool SHARED IMPORTED)

# Create imported target TKFillet
add_library(TKFillet SHARED IMPORTED)

# Create imported target TKFeat
add_library(TKFeat SHARED IMPORTED)

# Create imported target TKOffset
add_library(TKOffset SHARED IMPORTED)

# Create imported target TKCDF
add_library(TKCDF SHARED IMPORTED)

# Create imported target PTKernel
add_library(PTKernel SHARED IMPORTED)

# Create imported target TKLCAF
add_library(TKLCAF SHARED IMPORTED)

# Create imported target FWOSPlugin
add_library(FWOSPlugin SHARED IMPORTED)

# Create imported target TKPShape
add_library(TKPShape SHARED IMPORTED)

# Create imported target TKBinL
add_library(TKBinL SHARED IMPORTED)

# Create imported target TKXmlL
add_library(TKXmlL SHARED IMPORTED)

# Create imported target TKPLCAF
add_library(TKPLCAF SHARED IMPORTED)

# Create imported target TKTObj
add_library(TKTObj SHARED IMPORTED)

# Create imported target TKShapeSchema
add_library(TKShapeSchema SHARED IMPORTED)

# Create imported target TKStdLSchema
add_library(TKStdLSchema SHARED IMPORTED)

# Create imported target TKSTL
add_library(TKSTL SHARED IMPORTED)

# Create imported target TKXSBase
add_library(TKXSBase SHARED IMPORTED)

# Create imported target TKSTEPBase
add_library(TKSTEPBase SHARED IMPORTED)

# Create imported target TKIGES
add_library(TKIGES SHARED IMPORTED)

# Create imported target TKSTEPAttr
add_library(TKSTEPAttr SHARED IMPORTED)

# Create imported target TKSTEP209
add_library(TKSTEP209 SHARED IMPORTED)

# Create imported target TKSTEP
add_library(TKSTEP SHARED IMPORTED)

# Load information for each installed configuration.
get_filename_component(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
file(GLOB CONFIG_FILES "${_DIR}/OCE-libraries-*.cmake")
foreach(f ${CONFIG_FILES})
  include(${f})
endforeach()

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(target ${_IMPORT_CHECK_TARGETS} )
  foreach(file ${_IMPORT_CHECK_FILES_FOR_${target}} )
    if(NOT EXISTS "${file}" )
      message(FATAL_ERROR "The imported target \"${target}\" references the file
   \"${file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_IMPORT_CHECK_FILES_FOR_${target})
endforeach()
unset(_IMPORT_CHECK_TARGETS)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
